// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mexmxfkaafxupkprbxbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1leG14ZmthYWZ4dXBrcHJieGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDE5MzYsImV4cCI6MjA1ODgxNzkzNn0.95mnnzlL_yIfanCEBNcxAYikuTGn_ceQWxVnk08fOYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);